name: test3

on:
   push:
     branches:
      - main
jobs:
  upload:
      runs-on: ubuntu-latest
      steps:
       - name: update the os
         run: apt-get update -y
       - name: install cwosay
         run: apt install cowsay -y
       - name: create a cousay
         run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
       - name: update
         uses: actions/upload-artifact@v3
         with:
            name: my-dragon
            path: my-dragon

  download-test:
      needs: upload
      runs-on: ubuntu-latest
      steps:
       - name: update the os
         run: apt-get update -y
       - name: download
         uses: actions/download-artifact@v3
         with:
            name: my-dragon
          

       